type = "sfx"
priority = 10
[[steps]]
command = [38, 0, 9]
duration_frames = 4
[[steps]]
command = [45, 0, 10]
duration_frames = 4
[[steps]]
command = [50, 0, 10]
duration_frames = 4
[[steps]]
command = [57, 0, 11]
duration_frames = 14
[[steps]]
command = [255, 254, 0]
duration_frames = 1
