type = "sfx"
priority = 4

[[steps]]
command = [21, 1, 5]
duration_frames = 3

[[steps]]
command = [26, 1, 6]
duration_frames = 3

[[steps]]
command = [31, 0, 7]
duration_frames = 5

[[steps]]
command = [255, 254, 0]
duration_frames = 1
