type = "sfx"
priority = 7

[[steps]]
command = [31, 1, 8]
duration_frames = 3

[[steps]]
command = [21, 1, 6]
duration_frames = 4

[[steps]]
command = [12, 2, 5]
duration_frames = 6

[[steps]]
command = [255, 254, 0]
duration_frames = 1
